# Generated by Django 4.2.1 on 2024-09-12 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profi', '0002_doctors_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctors',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profi.doctors', verbose_name='Врач'),
        ),
    ]
